import CardContainer_CMP from "./CardContainer_CMP";
import ProductCard_CMP from "./ProductCard_CMP";
import Paginator_CMP from "./Paginator_CMP";
import SearchBar_CMP from "./SearchBar_CMP";
import LoadingSpinner_CMP from "./LoadingSpinner_CMP";
import CreateButton_CMP from "./CreateButton_CMP";
import ProductForm_CMP from "./ProductForm_CMP";
import Drawer_CMP from "./Drawer_CMP";
import { useDrawerUtils as DrawerUtils_CMP } from "./Drawer_CMP";
import Drawer_CLS from "./Drawer_CMPv2";
import NavBar_CMP from "./NavBar_CMP";
import { Main as Main_CMP } from "./NavBar_CMP";

export const CardContainer = CardContainer_CMP;
export const ProductCard = ProductCard_CMP;
export const Paginator = Paginator_CMP;
export const SearchBar = SearchBar_CMP;
export const Spinner = LoadingSpinner_CMP;
export const CreateButton = CreateButton_CMP;
export const ProductForm = ProductForm_CMP;
export const Drawer = Drawer_CMP;
export const useDrawerUtils = DrawerUtils_CMP;
export const DrawerClass = Drawer_CLS;
export const NavBar = NavBar_CMP;
export const Main = Main_CMP;
